name: Tests

on:
    push:
        branches:
            -master
            -dev
    pull_request:
        branches:
            -master
            -dev
jobs:
    hello-world:
        runs-on: ubuntu-20.04
        steps:
        - uses: actions/checkout@v2
        - run: echo 'Welcome to the Github Actions workshop !'
